### ISSUE TITLE
Issue collection

### ISSUE THREAD

**Issue by danielnaber** [danielnaber/firefox-dict-switcher#1]
To be done by danielnaber:
- [x] Evaluate: how many characters are needed, on average, to correctly detect the language? Then compare to https://github.com/wooorm/franc
- [x] deselected languages will not be considered, instead the language with the closest probability will be chosen
- [x] add mapping settings for: ~~Portuguese (Brazil, Portugal)~~, ~~English (New Zealand)~~, Norwegian (Bokmål, Nynorsk), Spanish (Spain, Argentina, Chile, Mexico), Tamil (India, Sri Lanka)
- [x] ~~add settings: drop-down of languages to ignore (3x)~~ let's first try if it works without, i.e. if detection quality is good enough
- [x] find better icon (maybe based on http://findicons.com/icon/58499/dictionary?id=58626,
  http://www.languageicon.org/, or flags with spell checker underlines?)
- [x] can we show a warning if no dictionary for the detected language is installed?

Collecting some issues/TODOs here:
- [x] changes to the `Ignore signature` (and other settings?) only become active after page reload, can these become active immediately?
- [x] settings: make sure there are useful defaults, i.e. a Firefox otherwise running in en-GB should of course have en-GB as default for English. The user should not need to visit the settings at all in those standard cases.
- [x] Visual feedback of selected dictionary and feedback when no dict has been selected yet. For example, show a small `en-US` symbol if English has been detected and `--` if nothing has been detected yet (text too short). Preferably the icon appears in the lower right corner of the textarea that is checked. ~~On hover, the icon should show a title like: `Detected English, selected British English from configuration`~~ -> partially done, see `showFeedback()` in `contentScript.js`
- [x] use a simple preferences dialog without the need to open a new tab
- [x] add setting `Ignore signature` (default: on): if activated, the text in a textarea after `-- \n` is not considered for language detection (useful for writing emails)
- [x] ~~When user has not set a dictionary mapping, do not just use the first from the list of mapping. Instead, have an internal hard-coded list of "best mappings": for English, the default is en-US, for German it's de-DE (but still, the first selection is the user's browser preference, see item above)~~ probably okay now, as we can just set what the first item is
- [x] As there are variants like "English (US)" and "English (GB)" which are difficult to distinguish, add a configuration interface where the user sets their preferred language. For example, if "English" is detected, the user might want the add-on to always use "English (GB)". Make sure there are useful defaults, i.e. a Firefox otherwise running in en-GB should of course have en-GB as default for English.
- [x] language detection works, now make dictionary switching work
- [x] Check performance: log the language detection time with `console.log`
- [x] Pasting text should trigger language detection
- [x] There should be no spell checking while we don't have enough text to avoid the confusing underlining
- [x] Detection doesn't always seem to be triggered at github, e.g. when creating a new bug report (https://github.com/danielnaber/firefox-dict-switcher/issues/new) or editing an existing one
- [x] add support for `contentEditable`

**Comment by ashrafsabrym** [comment]
I've done the first two issues.
As for the fourth, I noticed that it doesn't occur. The addon works well on Github. Maybe because the old code didn't handle elements appended dynamically.

**Comment by ashrafsabrym** [comment]
There was a problem in dictionaries initialization part. I fixed it. Now dictionaries should be swapped properly.
Also, I added contenteditable elements handling.

**Comment by ashrafsabrym** [comment]
- Done what were in the TODO comment
  // TODO: show language code including variant here
- Done the issue "can we show a warning if no dictionary for the detected language is installed?"
  You may need to modify the warning color and text.
- Done the issue "changes to the Ignore signature (and other settings?) only become active after page reload, can these become active immediately?"
  Now, the settings are always fresh without needing the user to reload the page.
