### ISSUE TITLE
sometimes doesn't work directly after start or installation

### ISSUE THREAD

**Issue by danielnaber** [danielnaber/firefox-dict-switcher#12]
Sometimes the focus event in a textarea doesn't seem to be trigger when the add-on has just been installed. Reloading the page help. Can also sometimes be reproduced when running with `cfx run` and a profile that opens the recently used tab at start.

**Comment by ashrafsabrym** [comment]
Every time the addon starts, either on installation or browser opening, I added code that iterates over all open tabs and attaches the script to those tabs that match our URL criteria.
