### ISSUE TITLE
change License

### ISSUE THREAD

**Issue by danielnaber** [danielnaber/firefox-dict-switcher#13]
Apache License is only supported as "Custom License" at https://addons.mozilla.org, we could use one of the supported licenses.

**Comment by danielnaber** [comment]
@ashrafsabrym Are you okay with a license change to MPL (https://www.mozilla.org/MPL/2.0/)? If so, please confirm here. The reason is that addons.mozilla.org displays the current License (Apache) as "Custom license" so on a first glance it looks as if we're using some strange license.

**Comment by danielnaber** [comment]
@ashrafsabrym @viraniac  Are you okay with a license change to MPL (https://www.mozilla.org/MPL/2.0/)? If so, please confirm here. The reason is that addons.mozilla.org displays the current License (Apache) as "Custom license" so on a first glance it looks as if we're using some strange license.

**Comment by ashrafsabrym** [comment]
Yes, it's okay. Change it to whatever you see appropriate.

**Comment by viraniac** [comment]
I am OK with license change as well.
