### ISSUE TITLE
Fixing "unsafe CPOW usage" warning

### ISSUE THREAD

**Issue by ashrafsabrym** [danielnaber/firefox-dict-switcher#14]
Maybe this is part of making the addon ready for the new multi process model that will be adopted in the near future Firefox versions.

When I run the addon in Firefox Developer Edition (which is currently version 41 of Firefox) this warning `unsafe CPOW usage` is raised whenever our code accesses a tab worker object.
CPOW stands for Cross Process Object Wrapper.

**Comment by danielnaber** [comment]
Does that still happen? Where exactly is the warning printed?

**Comment by ashrafsabrym** [comment]
No, I don't see it now with the current versions of the extension and Firefox developer edition
