### ISSUE TITLE
ignore URLs

### ISSUE THREAD

**Issue by danielnaber** [danielnaber/firefox-dict-switcher#15]
URLs should not be considered for language detection.

**Comment by ashrafsabrym** [comment]
This should be handled by the spell checking service itself.
If I write a URL with a protocol specifier (http://xyz.com), spell checking will ignore it. But if it has no protocol specifier (xyz.com), it will be checked.
I'm afraid that we can't control what and what not the spell checker marks as invalid. At least as far as I currently know about the API.

**Comment by danielnaber** [comment]
It's not about the checker but about language detection. If you have `http://myurl.com` in your string, the ngrams of that will be used to guess the languages, which usually doesn't make sense.

**Comment by ashrafsabrym** [comment]
Ok. We may write a RegEx to filter those.

**Comment by danielnaber** [comment]
Thanks, works fine for me.
