### ISSUE TITLE
Provide add-on signing

### ISSUE THREAD

**Issue by webron** [danielnaber/firefox-dict-switcher#18]
First  - thank you for this awesome add-on. I've been looking for something like it for a long time.

When using Firefox Nightly, they've added a requirement that add-ons must be signed otherwise they're disabled. 
<img width="738" alt="screenshot 2015-09-02 14 08 55" src="https://cloud.githubusercontent.com/assets/241629/9629561/307025bc-517c-11e5-8d01-d4ac5de44b52.png">

It would be great if you could perform the necessary steps to enable it, information can be found here - https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox?as=u&utm_source=inproduct.

**Comment by danielnaber** [comment]
When exactly did you install the add-on? It was reviewed a week or so ago and I think that includes signing (without there being a new version number). If your version is older, can you try re-install it?

**Comment by ashrafsabrym** [comment]
This is strange. I have the addon installed on Firefox Developer Edition 42.0a2 (2015-09-01) which is set to update from the aurora chanel, and it works properly.

May you uninstall the addon then install it again?

**Comment by webron** [comment]
Yup, reinstalling worked. I guess for the update to pick up automatically, it had to come as a new release (even if there's no functional change). I doubt it's going to hit many users, so not worth handling. Thanks for looking into it!
