### ISSUE TITLE
improve detection quality for short texts

### ISSUE THREAD

**Issue by danielnaber** [danielnaber/firefox-dict-switcher#2]
e.g.
mis-detected as 'en': `Zu wenig Text aber jetzt will ich doch mal etwas`
correctly detected: `Zu wenig Text aber jetzt will ich doch mal etwas ausprobieren`

**Comment by ashrafsabrym** [comment]
I'll inspect it. It looks so weird.
Just adding the word "das" makes it identify the text as German.
We may also report this to the library owners.

**Comment by ashrafsabrym** [comment]
The library gives English top detection score for this piece of text, next comes German.
Google detects it flawlessly. I hope we may use the library google uses.

**Comment by danielnaber** [comment]
I also found https://github.com/wooorm/franc, it looks well-maintained.

**Comment by danielnaber** [comment]
Using franc now, it's faster and better (see evaluation).
