### ISSUE TITLE
Any plans to support  Thunderbird?

### ISSUE THREAD

**Issue by jdittrich** [danielnaber/firefox-dict-switcher#22]
The addon’s function would be very useful for people writing mails in several languages. So I wonder if there are any plans to support Thunderbird?

 (I _may_ give this a try too, but it has been some time since my last attempts with add-ons)

**Comment by danielnaber** [comment]
As I'm not a Thunderbird user myself, I don't have plans to support it.

**Comment by jdittrich** [comment]
Thanks for the quick answer, @danielnaber. 

If anyone else is interested in this, @ me  :)
