### ISSUE TITLE
Flaky when composing Google Inbox messages (inbox.google.com)

### ISSUE THREAD

**Issue by marcbelmont** [danielnaber/firefox-dict-switcher#23]
The form to compose messages on Google new email client (inbox.google.com) must be doing something non-standard because the extension is not working well with it. Here are the steps to reproduce the bug:
- the extension is configured to detect English and French
- go to inbox.google.com
- create a new email
- start typing in English until the language detection is triggered
- click elsewhere to **un-focus** the compose form
- go back to the form, the language detection says English but **most valid words are marked as wrong** (red underline). The correct behavior would be, words that are valid don't get the red underline when you go back to the form.

**Comment by danielnaber** [comment]
This is a bug in Firefox, as discussed in #21. Unfortunately, we cannot really do anything unless this gets fixed in Firefox. It's not specific to Google Mail actually. We've taken the extension offline because of this.

**Comment by marcbelmont** [comment]
I hope it will get fixed soon. Thanks for letting me know.
