### ISSUE TITLE
Same functionality as a WebExtension

### ISSUE THREAD

**Issue by kimsey0** [danielnaber/firefox-dict-switcher#24]
I have implemented the same functionality as this addon has as a WebExtension: https://github.com/kimsey0/FirefoxAutoDict
Feel free to link users there, @danielnaber, if you like. (Also, I copied your choice of icon. Thanks for the inspiration. 😉)

**Comment by danielnaber** [comment]
Thanks, is it / will it be on https://addons.mozilla.org?

**Comment by kimsey0** [comment]
It's available at https://addons.mozilla.org/firefox/addon/automatic-spelling-language/
I should probably add that to the description on GitHub.

**Comment by danielnaber** [comment]
Thanks, I've linked it.
