### ISSUE TITLE
too much CPU usage

### ISSUE THREAD

**Issue by danielnaber** [danielnaber/firefox-dict-switcher#9]
While a textarea has focus, `requestAnimationFrame` uses too much CPU, around 50% on my computer. Could this be improved with e.g. `setTimeout`?

**Comment by ashrafsabrym** [comment]
This doesn't happen to me, but I admit that the technique is just brute-forcing and may cause high overheads.
What profiling tool do you use?

**Comment by danielnaber** [comment]
I see it's only 50% CPU usage if there are `console.log` calls for debugging, otherwise it's about 12%, but it should still be improved. I use no profiling tool but simply look at the computer's CPU usage (command `top` on Linux).

**Comment by ashrafsabrym** [comment]
Yes, I can see this behaviour. I get the 12% ratio too, which is to high for a dormant page. It makes my PC fan spin loudly.

The problem is that there's no reliable way to detect resize events on elements. I once stumbled upon a hack to enable them. I'll try and see if it works.

**Comment by danielnaber** [comment]
Added a `setTimeout` as a workaround, better solutions are welcome.

**Comment by ashrafsabrym** [comment]
As we used a lax `setTimeout` with 100 ms period, I removed `requestAnimationFrame` altogether as it's no longer needed.
I added a constant `feedBackDivRefreshRate` for the timer interval. If you want to further conserve CPU usage, increase its value, but feedback div positioning will be more sluggish.
